# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# source aliases
source ~/.private_aliases.sh
source ~/.public_aliases.sh

# for broot 
source "$HOME/.config/broot/launcher/bash/br"

# necessary for autojump
. /usr/share/autojump/autojump.sh






