# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# source aliases
if [[ -f  "$HOME/.private_aliases.sh" ]]; then
    source "$HOME/.private_aliases.sh"
fi

if [[ -f "$HOME/.public_aliases.sh" ]]; then
    source "$HOME/.public_aliases.sh"
fi

# for broot
if [[ -f "$HOME/.config/broot/launcher/bash/br" ]]; then
    source "$HOME/.config/broot/launcher/bash/br"
fi

# necessary for autojump
. /usr/share/autojump/autojump.sh






